[theme]
# Professional security-themed color scheme
primaryColor = "#FF4B4B"  # Red for warnings
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F2F6"  # Light gray
textColor = "#31333F"  # Dark gray text
font = "sans serif"

[server]
# Security optimizations
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10  # MB
